### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#246]
Create 404 page that shows up when a user navigates to a page that is not defined in Urls const

**Comment by eoncarlyle** [comment]
@thegrims I'll try to take care of this on Saturday

**Comment by zakpatterson** [comment]
To be clear though this is not actually a 404 error since the user is served the html whenever the server gets a request that doesn't match one of the static files it has. 

Then if the route doesn't match we can either show an error page or a redirect to a default page. If we had a descriptive Get Started page I think that would be a good place to redirect to. Until then I think an error page is good.

**Comment by thegrims** [comment]
The page not found PR has been successfully merged and deployed
