### ISSUE TITLE
AGPL License 

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#504]
> don't know if you are the developer but since it's a server it's probably best to use the agpl instead of the gpl, it is a slightly modified version of the gpl that enforces copyleft on serves (read more here: https://www.gnu.org/licenses/why-affero-gpl.html)
> 
> (would open an issue on github but i've been banned and making a new account is too annoying)

https://www.reddit.com/r/freesoftware/comments/otqezh/open_source_tax_filing_website/h70bvpz?utm_source=share&utm_medium=web2x&context=3

**Comment by GMNGeoffrey** [comment]
Hey just wanted to drop a note here because I came across this project, thought it was cool, and then was sad to learn that it was licensed under AGPL. Switching form GPL to AGPL is absolutely not the quick "oh this is reasonable" decision presented here. AGPL is hotly contested across the internet (random examples from internet search. not authoritative): https://news.ycombinator.com/item?id=24764481, https://www.techrepublic.com/article/dont-believe-the-hype-agpl-open-source-licensing-is-toxic-and-unpopular/, and https://medium.com/swlh/understanding-the-agpl-the-most-misunderstood-license-86fd1fe91275.

IANAL and so will not offer my personal take on this whole debate, but it's definitely not without its downsides. Of particular relevance to me is the policy of Google (my employer): https://opensource.google/documentation/reference/using/agpl-policy. Companies just absolutely don't want to touch this stuff because it infects an entire codebase and is full of ambiguities. Google's lawyers are on the conservative side with this sort of thing, but they're not pulling this from nowhere. A follow-on from that is that it's also Google's policy not to contribute to AGPL projects: https://opensource.google/documentation/reference/patching#forbidden.

So anyway, do whatever you want with your project, obviously, but I wanted to make you aware of some of the effects here. Sad for me because I'm not going to use an OSS project I can't contribute to.

**Comment by zakpatterson** [comment]
> So anyway, do whatever you want with your project, obviously, but I wanted to make you aware of some of the effects here. Sad for me because I'm not going to use an OSS project I can't contribute to.

Thanks for your comment. Can you elaborate on why your employer's position with respect to AGPL affects your ability to contribute?

**Comment by GMNGeoffrey** [comment]
The IP clause in Google employment contracts is pretty broad. They assert that they have copyright for anything I do that "relates to my work for Google or Google's business" or something like that. Writing code in OSS is what I do as my job, so it's difficult to disentangle that from things I do personally. There's a whole process for creating a clear separation (https://opensource.google/documentation/reference/releasing#iarc, that's all that's public, I think), but it's a huge pain and definitely not worth it for this sort of thing. It's not really clear what happens if you don't get explicit approval (again IANAL). If something has an allowed license (which is most of the major ones) then there's no problem. Maybe Google owns the copyright for my contribution, but it's under a permissive license so who cares: anyone can use it.

**Comment by zakpatterson** [comment]
I'd like to hear other perspectives but my initial impression is that the license is working quite nicely if it's stopping a large company from laying claim to copyright of a contribution.

**Comment by GMNGeoffrey** [comment]
🤷 It's stopping the contribution from happening entirely. I'm certainly not thrilled with broad IP clauses in employment contracts nor the general nature of intellectual property law. I don't know what you think would happen if for some reason the possessor of copyright were a company of any particular size, given that licensing under a permissive license allows anyone to use it regardless.

But anyways, I just left a note here because it seemed like perhaps you'd made this decision not realizing what exactly it meant. If your goal is to avoid engagement from commercial entities, then yes this is perhaps the right license for you. I'm not particularly interested in having an argument about licenses.
