### ISSUE TITLE
Support capital gains income (1099 B), Schedule D

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#69]
Should be able to add data from multiple 1099 B forms, pdf output should include schedule D and accumulate to field number 64 on the 1040.

Todos:
* [x] [Schedule D or Capital Gains and Qualified Dividends worksheet](https://www.irs.gov/instructions/i1040sd#idm140312989632848)
* [x] Schedule D
* [x] Lines on 1040 (3a, 7)

Dealing with uncovered and unreported transactions is a separate issue:
* [ ] Schedule 8949 - used when basis is not reported to IRS, or for capital gains that are not reported on 1099B.
    * There are a number of types of transactions to report here:
        * (B) Short-term basis unreported transactions - required
        * (C) Short-term transactions not reported on form 1099-B - required
        * (E) Long-term basis unreported transactions - required
        * (F) Long-term transactions not reported on form 1099-B - required
    * User should be able to add list of transactions for B, C, E, F (note we should determine long term / short term)

**Comment by thegrims** [comment]
@zakpatterson  I think before capital gains and interest income are added the tax calculation 1040 fields 1-38 should be filled with default values or calculated so that the tax calculator gets to a very minimum viable product where someone could file their taxes on it if they fit a specific profile
