### ISSUE TITLE
Uncaught (in promise) Error: Validation Failed: /box12/DD: must be number || Numeric value passed as string

### ISSUE THREAD

**Issue by gnoejuan** [ustaxes/UsTaxes#879]
Looking at the console, it looks like the value is stored as a string. The other fields, such as income, show as a number. ​

Numbers changed for reasons
income: 00000.00, medicareIncome: 000000.00,

as opposed to

box12: {
...
DD: "0000.00"
...
}

**Comment by gnoejuan** [comment]
I'm not familiar enough with react to suggest a fix, at the moment.

I see that the working field (income) has the same setup as the non-working field.

<input aria-invalid="false" id="income" name="income" type="text" class="MuiInputBase-input MuiFilledInput-input MuiInputBase-inputAdornedStart MuiFilledInput-inputAdornedStart" value="000.00" data-com.bitwarden.browser.user-edited="yes">

<input aria-invalid="false" id="box12.DD" name="box12.DD" type="text" class="MuiInputBase-input MuiFilledInput-input MuiInputBase-inputAdornedStart MuiFilledInput-inputAdornedStart" value="000.00">

**Comment by dweiss2** [comment]
I have the same error. I can't save my W-2 because of this. When I checked the console it seems all values for box 12 are strings and should be numbers. In the dump below all actual dollar values changed to XXX.XX for obvious reasons.

`A: undefined
AA: undefined
B: undefined
BB: undefined
C: "XXX.XX"
D: "XXX.XX"
DD: "XXX.XX"
E: undefined
EE: undefined
F: undefined
FF: undefined
G: undefined
GG: undefined
H: undefined
HH: undefined
J: undefined
K: undefined
L: undefined
M: undefined
N: undefined
P: undefined
Q: undefined
R: undefined
S: undefined
T: undefined
V: undefined
W: "XXX.XX"
Y: undefined
Z: undefined`

**Comment by dweiss2** [comment]
@gnoejuan I figured out a workaround.

1.  Fill out all other boxes of the W-2 and critically, do not hit "Edit" for line 12. 
2. Go to the app settings (ustaxes.org/settings) with the gear icon and save to data file.
3. Open the exported json and add the appropriate information to the blank box 12 object; `"box12: {}` changes to `box12: {"D": 0000.00}`
4. Back in the settings, load the modified json.

**Comment by zakpatterson** [comment]
Thanks so much @gnoejuan and @dweiss2 for this well explained report. We developed a fix for this as well as #880, and it should be live soon. You're welcome to try it here: https://deploy-preview-881--ustaxes.netlify.app/

You should be able to save your json file as you mentioned from the live version, then import it into the preview.

Thanks for the feedback!!

**Comment by thegrims** [comment]
This bug should be fixed now on the site! Thanks, @gnoejuan  @dweiss2
